=== sfvishalgupta/my_opentrons/shared-data/robot/schemas/1.json
{
  "$id": "opentronsRobotSchemaV1",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "robotType": {
      "type": "string",
      "enum": ["OT-2 Standard", "OT-3 Standard"]
    },
    "xyzArray": {
      "type": "array",
      "description": "Array of 3 numbers, [x, y, z]",
      "items": { "type": "number" },
      "minItems": 3,
      "maxItems": 3
    }
  },
  "description": "Describes an Opentrons liquid handling robot.",
  "type": "object",
  "required": ["displayName", "robotType", "models", "extents", "mountOffsets"],
  "properties": {
    "displayName": {
      "description": "A user-facing friendly name for the machine.",
      "type": "string"
    },
    "robotType": {
      "description": "A machine-readable but still printable name for the machine.",
      "$ref": "#/definitions/robotType"
    },
    "models": {
      "description": "A list of robot models.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "extents": {
      "description": "The maximum addressable coordinates of the deck without instruments.",
      "$ref": "#/definitions/xyzArray"
    },
    "paddingOffsets": {
      "description": "The distance from a given edge of a deck extent by which the maximum amount of travel is limited.",
      "type": "object",
      "required": ["rear", "front", "leftSide", "rightSide"],
      "properties": {
        "rear": {
          "description": "The padding distance from the rear edge of the deck extents which the front nozzles of a pipette must not exceed.",
          "type": "number"
        },
        "front": {
          "description": "The padding distance from the front edge of the deck extents which the rear nozzles of a pipette must not exceed.",
          "type": "number"
        },
        "leftSide": {
          "description": "The padding distance from the left edge of the deck extents which the right-most nozzles of a pipette must not exceed.",
          "type": "number"
        },
        "rightSide": {
          "description": "The padding distance from the right edge of the deck extents which the left-most nozzles of a pipette must not exceed.",
          "type": "number"
        }
      }
    },
    "mountOffsets": {
      "description": "The physical mount offsets from the center of the instrument carriage.",
      "type": "object",
      "required": ["left", "right"],
      "properties": {
        "left": {
          "description": "The left mount offset from the center of the carriage to the center of the left mount",
          "$ref": "#/definitions/xyzArray"
        },
        "right": {
          "description": "The right mount offset from the center of the carriage to the center of the right mount",
          "$ref": "#/definitions/xyzArray"
        },
        "gripper": {
          "description": "The gripper mount offset from the center of the carriage to the center of the gripper, only on OT-3 Standard definitions",
          "$ref": "#/definitions/xyzArray"
        }
      }
    }
  }
}

=== sfvishalgupta/my_opentrons/shared-data/robot/definitions/1/ot2.json
{
  "displayName": "OT-2",
  "robotType": "OT-2 Standard",
  "models": ["OT-2 Standard", "OT-2 Refresh"],
  "extents": [446.75, 347.5, 0.0],
  "paddingOffsets": {
    "rear": -35.91,
    "front": 31.89,
    "leftSide": 0,
    "rightSide": 0
  },
  "mountOffsets": {
    "left": [-34.0, 0.0, 0.0],
    "right": [0.0, 0.0, 0.0]
  }
}

=== sfvishalgupta/my_opentrons/shared-data/robot/definitions/1/ot3.json
{
  "displayName": "OT-3",
  "robotType": "OT-3 Standard",
  "models": ["OT-3 Standard"],
  "extents": [477.2, 493.8, 0.0],
  "paddingOffsets": {
    "rear": -177.42,
    "front": 51.8,
    "leftSide": 31.88,
    "rightSide": -80.32
  },
  "mountOffsets": {
    "left": [-13.5, -60.5, 255.675],
    "right": [40.5, -60.5, 255.675],
    "gripper": [84.55, -12.75, 93.85]
  }
}
